<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
	</ItemGroup>
  <ItemGroup>
    <Compile Remove="CustomEntities\**" />
    <EmbeddedResource Remove="CustomEntities\**" />
    <None Remove="CustomEntities\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Ground\ECommerce.Ground.csproj" />
  </ItemGroup>

</Project>
